### ISSUE TITLE
Version 1.4 problem

### ISSUE THREAD

**Issue by shbeavers** [Thomas008/robust_excel_ole#10]
In version 1.2, the all lowercase method 'value' would work in the reference sheet[R,C].value.
In 1.4 the method must be capitalized 'Value' as in the reference sheet[R,C].Value or else it fails due to a "missing method" error.
Having a capitalized method name is contrary to Ruby conventions.  It should be changed to all lowercase.
The capitalized 'Value' method name is used in the robust_excel_ole documentation and should be corrected there as well.

**Comment by Thomas008** [comment]
I did a change that caused incompatibility: the method 'Value' is actually not a ruby method but a VBA method. I did not wanted to allow anymore a method starting with a lower case letter to be interpreted as VBA method, but that only methods starting with upper case letter are interpreted as VBA method.
Sorry for any inconvenience. In the new commit this is repaired such that 'value' works fine again.

**Comment by Thomas008** [comment]
Yes, capitalized method names are contrary to Ruby conventions. In this exactly this sense, in RobustExcelOle a capitalized letter method is not meant as a Ruby method, but a VBA method. In future version, only capital letter methods (and not lower letter methods as well) shall be interpreted as a VBA methods. This has the advantage, that the user must be aware that she is sending a VBA method, and to prevent, that the user is sending a VBA method she did not want to.

 

I added the method Range#v, Cell#v, returning the value of a range or cell.

 

So valid expressions would be

 

range.v

=> [["foo",nil,"bar"],[nil,nil,"fke"]]

 

sheet[1,1].v

=> "foo"

 

Best,

Thomas
 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Freitag, 19. Oktober 2018 um 01:32 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Thomas008/robust_excel_ole] Version 1.4 problem (#10)


In version 1.2, the all lowercase method 'value' would work in the reference sheet[R,C].value.
In 1.4 the method must be capitalized 'Value' as in the reference sheet[R,C].Value or else it fails due to a "missing method" error.
Having a capitalized method name is contrary to Ruby conventions. It should be changed to all lowercase.
The capitalized 'Value' method name is used in the robust_excel_ole documentation and should be corrected there as well.

**Comment by shbeavers** [comment]
Hi Thomas,
This is a perfectly good convention, to have VBA methods capitalized and Ruby methods in all lower case.  This should be mentioned prominently in the documentation, if only so user know to watch for capitalized and un-capitalized methods.  In the case of V/value, I got confused when it changed.

Your other email today about how to paste values only and to transpose was very enlightening.  I look forward to trying out these techniques.

I always appreciate your responsiveness.  Thank you for your help.
Best,Scott
