### ISSUE TITLE
weird error when included gem

### ISSUE THREAD

**Issue by dsisnero** [Thomas008/robust_excel_ole#3]
I kept on getting an error on Kernel method Array and traced it to when requiring this gem.

Array('this')
 pry(main)> Array('this')
["this"]
 pry(main)> Array(1)
[1]
 pry(main)> require 'robust_excel_ole'
true
 pry(main)> Array('this')
ethodError: undefined method `each' for "this":String
m (pry):4:in `to_a'
 pry(main)> Array(1)
ethodError: undefined method `each' for 1:Integer
m (pry):5:in `to_a'
 pry(main)>

I am not sure why this happens because I see no redefinition of the method

**Comment by Thomas008** [comment]
Hi!

Thank you a lot for pointing out this error in RobustExcelOle.

Sorry for the delay!
We improved the program now, and hope the error does not occur anymore.

When you have any further comments, suggestions or questions, we are happy to hear from you.

Thanks a lot!

Thomas


 

---
Dr. Thomas Raths
Körperpsychotherapie, Wasser-Körperarbeit, Tanz

Karmeliterweg 49
13465 Berlin-Frohnau

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Mittwoch, 28. Juni 2017 um 16:50 Uhr
Von: dsisnero <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Thomas008/robust_excel_ole] weird error when included gem (#3)


I kept on getting an error on Kernel method Array and traced it to when requiring this gem.

Array('this')
pry(main)> Array('this')
["this"]
pry(main)> Array(1)
[1]
pry(main)> require 'robust_excel_ole'
true
pry(main)> Array('this')
ethodError: undefined method each' for "this":String m (pry):4:into_a'
pry(main)> Array(1)
ethodError: undefined method each' for 1:Integer m (pry):5:into_a'
pry(main)>

I am not sure why this happens because I see no redefinition of the method
