### ISSUE TITLE
Error in 'Range' Documentation

### ISSUE THREAD

**Issue by shbeavers** [Thomas008/robust_excel_ole#5]
Re: https://github.com/Thomas008/robust_excel_ole/blob/master/docs/README_ranges.rdoc

The error is in the last statement that shows 'worksheet.set_name' parameters are in this order:
worksheet.set_range(row, col, **"name"**) when "name" is actually the first parameter, i.e.,
worksheet.set_range(**"name"**, row, col).  It would also be very helpful to point out that a range may encompass more than a single cell by declaring '1..x' in the row and/or col parameters. 

Since your entire discussion of range assumes that you have a named range, the explanation of 'set_range' should appear at the top of the document - as well as the clarification that this is or isn't the only way to work with ranges without using loops.  Capabilities for reading are much more clearly defined than for writing.

Further, it appears that the only way to avoid using loop(s) to write an array of values into a row or column is to establish a range is by naming it.  If there's an alternative, an example or two would be worthwhile.

**Comment by Thomas008** [comment]
Hello,

thank you a lot for pointing this error and clarifying the meaning of a range and the related issues. I will fix it this week.
I would be interested: Do you apply this gem, RobustExcelOle, and what further suggestions or needs do you have?


Best regards,

 

Thomas

 

 

Gesendet: Montag, 27. August 2018 um 17:19 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)


Re: https://github.com/Thomas008/robust_excel_ole/blob/master/docs/README_ranges.rdoc

The error is in the last statement that shows 'worksheet.set_name' parameters are in this order:
worksheet.set_range(row, col, "name") when "name" is actually the first parameter, i.e.,
worksheet.set_range("name", row, col). It would also be very helpful to point out that a range may encompass more than a single cell by declaring '1..x' in the row and/or col parameters.

Since your entire discussion of range assumes that you have a named range, the explanation of 'set_range' should appear at the top of the document - as well as the clarification that this is or isn't the only way to work with ranges without using loops. Capabilities for reading are much more clearly defined than for writing.

Further, it appears that the only way to avoid using loop(s) to write an array of values into a row or column is to establish a range is by naming it. If there's an alternative, an example or two would be worthwhile.

**Comment by shbeavers** [comment]
Thomas,
Good to hear from you.  I'm very impressed with what I've seen so far.  

I've only just started working with the gem and will report back what I find.  However, I won't be doing anything too complicated right now:  opening and creating, saving and closing, pasting data into a range of cells in a column, and copying part of a row of calculated results into another row - values only, without formulas.

In testing at the command line I've experienced episodes where workbook methods can't be found.  It's too early to say if I'm causing this or not.  If it's me, I'll let you know so you can tell other users what to avoid doing.  Nor am I sure that this is not being caused by some interaction with pry.  I'll go to a point in my program where I've set up a workbook and worksheet and then pause with pry and try next steps manipulating the file at the command line to confirm the exact syntax.  I'm pretty new to Ruby so I'm very creative about how I screw up using methods.
Scott

**Comment by Thomas008** [comment]
I have fixed the docu.

**Comment by Thomas008** [comment]
Inspired by your comment, we plan to improve the documentation by clear examples (using VBA methods), and to extend the implementations from cells to (rectangular) ranges.

**Comment by shbeavers** [comment]
Thanks for the update.  I'm very interested in how to select, copy, and paste a row or column across workbooks with looping cell by cell.  Must ranges always be named?

I'll have some more input soon.  I'll email directly to you because I want to give some background on what I was doing when I ran into trouble - too much verbiage for an issue report.
Scott

**Comment by Thomas008** [comment]
Dear Scott,
I'm happy about your interest. You inspire to ideas for useful extensions
Regarding selecting a row and a column, so far there are only rudimentary methods in the class Sheet: Sheet#row_range and Sheet#col_range. I would extend it.

So far ranges must be named. I'm wondering about other ways to refer to ranges.

So far. Let's stay in contact.

Thomas
 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Sonntag, 02. September 2018 um 18:58 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)

Thanks for the update.  I'm very interested in how to select, copy, and paste a row or column across workbooks with looping cell by cell.  Must ranges always be named?

I'll have some more input soon.  I'll email directly to you because I want to give some background on what I was doing when I ran into trouble - too much verbiage for an issue report.
Scott

**Comment by shbeavers** [comment]
Dear Thomas,
I want to say upfront that I think RobustExcelOle is an excellent piece of work.  It's ambitious and I recognize that it's a work in progress but I feel you've taken the best approach for delivering an extensive range of Excel functionality.  I feel very fortunate to have come across it when I did because I was about to start developing a basic OLE interface to Excel for myself.  Thank you for your work!

Let me give you a little background on the makeup of my project before discussing where I've had problems.
I'm automating the process of downloading of information from a website.  This data happens to download in a tab delimited text file which RobustExcelOle opens without issue.  I then copy a particular column of the downloaded file.into a separate spreadsheet that contains a selection of formulas for analyzing the data that was copied in.  Finally, a large section of one row that contains the analyzed values is copied and pasted into a collection area of the spreadsheet.  This process is repeated 50 to 100 times with a new section of analyzed data added to the collection area with each cycle.  Ultimately, the characteristics of the collected rows are further analyzed for correlation information.
The program is written in Ruby using the Selenium WebDriver to interact with the target website.  The program has no front panel or browser interface.  The program is started from a command line - either IRB or Windows PowerShell and and a few execution parameters are read out of a Setup spreadsheet containing things like the website URL and number of cycles to run.  I recently abandoned RubyXL in favor Robust because Robust allows me to have the spreadsheet Calculate on command as well as providing copy and paste capabilities.
I should also add that I've been programming in Ruby for less than 2 months after a gap of around 15 years, at which time I was primarily using LabVIEW.  Some of my issues may be my unfamiliarity with current syntax formats.  Statements that may be perfectly clear could seem a bit obtuse to me coming from a background in languages like FORTH, C, C++, and various assembly languages.

Now for some information on my experience with Robust:   
   - either during initialization or within the first few Robust calls I get a warning about Fixnum being deprecated.  I believe this indicates a potential for future problems.
   - I would like to be able to copy and paste rows, columns, or areas in a single operation like I can manually.  I can't figure out if this is possible using named ranges or row_range in some way.  Currently I use loops to transfer cell block one cell at a time.  If there is another way, a programming example would be most useful.   

   - Based on my experience using Excel manually, I did not expect that ranges would need to be named, just declared in some upper-left/lower-right cell fashion.  So I spent a goodly amount of time reading and re-reading the documentation before letting go of my preconception.  I think a clear statement should be made upfront that range functionality is available only for named ranges.
   - I understand that row_range and col_range can be used to copy and paste cells from one worksheet to another but I couldn't determine if - or how - to copy and paste between workbooks.
   - I'd also like to be clear how to copy partial rows or columns as a block.   

   - I wanted to have my program use it's own instance of Excel so it wouldn't affect or be affected by other Excel activities on the same machine.  I didn't want to accidentally close someone else's already open workbook or have some user opening their own workbook in 'my' instance because it was the most recently opened instance.
   
   - I couldn't find a way to assure that no one else would be able to use my instance, keeping the instance reserved only for my files.
   - occasionally some internet problem would occur that crashed my program, which is capable of resuming at the cycle that got cut off.  However, since I would have no record of which instance I was working with before the crash, I'd create a new Excel on resuming and my files would become read-only in to the new instance.  I would also end up with read-only access to the files launching Excel manually.  I tried closing the files whenever I wasn't accessing them and reopening only as needed.  Having the files closed most of the time did not fix the read-only problem.
   - I tried to work around this issue by using open_unobtrusively or for_reading.  I was completely unable to figure out from the documentation how to incorporate rw_change_excel.  I tried over a dozen approaches and could not construct a statement that would work with some combination of these factors.
My takeaway regarding Robust's Excel instances capability is that the documentation is insufficient to enable application of the feature under the circumstances I desire.  Again, some added programming examples - or even just examples of how to construct Robust statements that will execute - would be very useful in this area.  I found the information earlier in the document about opening a workbook with :visible, etc. to be perfectly informative.  The document I'm referring to is robust_excel_ole/docs/README_open.rdoc 
Again, at least some of this could be a case of my lack of experience with modern programming conventions and syntax.  I certainly believe that the features you've documented do actually work.  I just couldn't get them to.
One idea that might be generally helpful with documenting:  think of what users are used to doing manually and try to explain how to do those things programmatically with Robust.  This is also a perspective that could be useful for prioritizing feature extension.  I had almost as much trouble with missing features I expected to be there as I did with inscrutable documentation.  BTW: since I didn't see a 'Paste As' capability mentioned, I was delighted that copying and pasting formula cells defaulted to 'Value Only' so there was no issue with the formulas copying, too.
Again, you're some really good work here. I don't want to spend too much time being picky about things without acknowledging that you should feel good about what you've accomplished.
Scott

**Comment by Thomas008** [comment]
Dear Scott,
first I really thank you a lot for your interest and your feedback. This is very valuable for the further progress of RobustExcelOle, and inspires already to extensions of the gem. I want to extend RobustExcelOle and take your requests into account. I want to admit that I have not so much advanced experience with Excel, so it is good to hear what you need.Here are first comments to your requests and feedback.

- For copy & paste:
Note that you can apply all VBA methods that you would do manually, you can send to a Workbook (Robust Excel) object, starting with capital letter.
For example:
workbook = Workbook.open('spec/data/workbook.xls')
sheet = workbook.sheet(1)
col = sheet.col_range(1)
col.Copy("destination" =>  s.row_range(3).ole_range)
We plan to supply a single operation for that
- copying and pasting between workbooks does not work yet. We work on that.
- Partial rows and columns
col2 = sheet.row_range(1,2..4) # cells 2 to 4 in the 1st row
- Excel ranges need not be named of course - you are right.
For example,
col = sheet.col_range(1)
row = sheet.row_range(1,2..4)
We want to extend it to rectangular ranges
- For opening workbooks in your Excel instance we will extend the method Book#open with another parameter
('reserved')
- Fixing the read-only problem after a crash, it might help to terminate all Excel instances using
Excel.kill_all

 

I hope that gives a first hint. We inform you as soon we have finished some things (one or two weeks). I will put some issues into git hub.

 

Best,

Thomas

 

 

 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Dienstag, 04. September 2018 um 07:01 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)

Dear Thomas,
I want to say upfront that I think RobustExcelOle is an excellent piece of work.  It's ambitious and I recognize that it's a work in progress but I feel you've taken the best approach for delivering an extensive range of Excel functionality.  I feel very fortunate to have come across it when I did because I was about to start developing a basic OLE interface to Excel for myself.  Thank you for your work!

Let me give you a little background on the makeup of my project before discussing where I've had problems.
I'm automating the process of downloading of information from a website.  This data happens to download in a tab delimited text file which RobustExcelOle opens without issue.  I then copy a particular column of the downloaded file.into a separate spreadsheet that contains a selection of formulas for analyzing the data that was copied in.  Finally, a large section of one row that contains the analyzed values is copied and pasted into a collection area of the spreadsheet.  This process is repeated 50 to 100 times with a new section of analyzed data added to the collection area with each cycle.  Ultimately, the characteristics of the collected rows are further analyzed for correlation information.
The program is written in Ruby using the Selenium WebDriver to interact with the target website.  The program has no front panel or browser interface.  The program is started from a command line - either IRB or Windows PowerShell and and a few execution parameters are read out of a Setup spreadsheet containing things like the website URL and number of cycles to run.  I recently abandoned RubyXL in favor Robust because Robust allows me to have the spreadsheet Calculate on command as well as providing copy and paste capabilities.
I should also add that I've been programming in Ruby for less than 2 months after a gap of around 15 years, at which time I was primarily using LabVIEW.  Some of my issues may be my unfamiliarity with current syntax formats.  Statements that may be perfectly clear could seem a bit obtuse to me coming from a background in languages like FORTH, C, C++, and various assembly languages.

Now for some information on my experience with Robust:
- either during initialization or within the first few Robust calls I get a warning about Fixnum being deprecated.  I believe this indicates a potential for future problems.
- I would like to be able to copy and paste rows, columns, or areas in a single operation like I can manually.  I can't figure out if this is possible using named ranges or row_range in some way.  Currently I use loops to transfer cell block one cell at a time.  If there is another way, a programming example would be most useful.

- Based on my experience using Excel manually, I did not expect that ranges would need to be named, just declared in some upper-left/lower-right cell fashion.  So I spent a goodly amount of time reading and re-reading the documentation before letting go of my preconception.  I think a clear statement should be made upfront that range functionality is available only for named ranges.
- I understand that row_range and col_range can be used to copy and paste cells from one worksheet to another but I couldn't determine if - or how - to copy and paste between workbooks.
- I'd also like to be clear how to copy partial rows or columns as a block.

- I wanted to have my program use it's own instance of Excel so it wouldn't affect or be affected by other Excel activities on the same machine.  I didn't want to accidentally close someone else's already open workbook or have some user opening their own workbook in 'my' instance because it was the most recently opened instance.

- I couldn't find a way to assure that no one else would be able to use my instance, keeping the instance reserved only for my files.
- occasionally some internet problem would occur that crashed my program, which is capable of resuming at the cycle that got cut off.  However, since I would have no record of which instance I was working with before the crash, I'd create a new Excel on resuming and my files would become read-only in to the new instance.  I would also end up with read-only access to the files launching Excel manually.  I tried closing the files whenever I wasn't accessing them and reopening only as needed.  Having the files closed most of the time did not fix the read-only problem.
- I tried to work around this issue by using open_unobtrusively or for_reading.  I was completely unable to figure out from the documentation how to incorporate rw_change_excel.  I tried over a dozen approaches and could not construct a statement that would work with some combination of these factors.
My takeaway regarding Robust's Excel instances capability is that the documentation is insufficient to enable application of the feature under the circumstances I desire.  Again, some added programming examples - or even just examples of how to construct Robust statements that will execute - would be very useful in this area.  I found the information earlier in the document about opening a workbook with :visible, etc. to be perfectly informative.  The document I'm referring to is robust_excel_ole/docs/README_open.rdoc
Again, at least some of this could be a case of my lack of experience with modern programming conventions and syntax.  I certainly believe that the features you've documented do actually work.  I just couldn't get them to.
One idea that might be generally helpful with documenting:  think of what users are used to doing manually and try to explain how to do those things programmatically with Robust.  This is also a perspective that could be useful for prioritizing feature extension.  I had almost as much trouble with missing features I expected to be there as I did with inscrutable documentation.  BTW: since I didn't see a 'Paste As' capability mentioned, I was delighted that copying and pasting formula cells defaulted to 'Value Only' so there was no issue with the formulas copying, too.
Again, you're some really good work here. I don't want to spend too much time being picky about things without acknowledging that you should feel good about what you've accomplished.
Scott

**Comment by shbeavers** [comment]
Thomas,
Thanks so much for getting back to me.  It feels very productive to have these interactions.

I'm not familiar with Excel VBA methods but can check documentation.  It might be a good idea to suggest that your users can check VBA documentation and maybe give them a link.
Thank you for showing me how to set ranges without using a name.  It makes perfect sense that you can assign a variable instead of a name to a range.

You example is mostly clear except for the last line:    workbook = Workbook.open('spec/data/workbook.xls')
    sheet = workbook.sheet(1)    
    col = sheet.col_range(1)
    col.Copy("destination" =>  s.row_range(3).ole_range)
I understand opening the workbook and worksheet then setting 'col' to the range of column 1.  I also understand that you are using the Copy method to copy column 1 to another location.  What I don't understand is:   
   - what is "destination"? The rocket equals ('=>') in Ruby means set an enum value and would use a ':name' type entry.  Am I right that statement intent is "col.Copy(:destination => s.row_range(3).ole_range)"?
   - what is "s" in the destination s.row_range... ?  Did you mean "sheet"?  Were you showing how to copy to a different worksheet in this example (worksheet 's' instead of worksheet 'sheet')?   

   - are you copying column 1 to row 3, that is, transposing the column?  Is this how you would transpose?  Or did you intend to say 'col_range' rather than 'row_range'   

   - lastly, what does the ".ole_range" signify, that is, why is it required?  This is not something I've seen in your previous documentation.   


I suspect some of the confusion comes from translating VBA syntax to Ruby syntax.
I'm surprised that copying a range between workbooks doesn't work.  I have copied individual cells between workbooks.  I fact, I've copied a range between workbooks using a loop to copy one cell at a time.  Now that I understand copying ranges a bit better, I'd think that setting up variables for a second workbook and worksheet would allow copying between them.  As in adding these lines to your example:    workbook2 = Workbook.open('spec/data/workbook2.xls')
    sheet2 = workbook2.sheet(1) 
then, per your example:    col = sheet.col_range(1)    col.Copy("destination" => sheet2.row_range(3).ole_range)
At least, this is the form I'd expect for copying a range between workbooks - probably with the last line changed for Ruby per my earlier comments.

About the read-only problem, I had the same idea you suggested and wrote a little utility that executes 'RobustExcelOle::Excel.kill_all'.  Of course, you must be sure every other open Excel file is properly saved before using it so I may want to add a warning message.
I think I understand what 'reserved' is intended to do.  I can always create a new Excel instance for my program but anyone else opening a spreadsheet after that will likely start using my instance.  This means they get closed down along with me when I'm done.  This is the problem 'reserved' will solve

My only problem is that when my program has crashed I won't know when I reboot which open instance of Excel has been reserved for my use.  What if I write a reference to that instance into the same Setup spreadsheet that I use for reading other configuration parameters into the program when it boots.

Maybe you know if this will work?  I should test it.  If I can read in my Excel instance, I can also have my 'terminate Excel' utility read in and terminate just my program's Excel instance and not disrupt any other Excel activities on my system.  And if the program can't find the recorded instance, it can just create a new one and then write it to Setup.
Thanks again for all your great work.
Best,
Scott

**Comment by Thomas008** [comment]
Dear Scott,

thank you for this quick feedback.
 

Here are first answers:
In the statement

col.Copy("destination" =>  sheet.row_range(3).ole_range)

is destination a parameter of the VBA Copy statement
I forgot the link, here it is:

https://msdn.microsoft.com/de-de/vba/excel-vba/articles/range-copy-method-excel

And yes, it is not 's' but sheet.row:rage(3) etc.

The ole_range refers to the WIN32OLE object of a range, and is new.

So you would have to git pull again.

It does not matter, wheter "destination" or :destination.

 

The copying and pasting does not seem to work yet.

We are still working on that issue.

 

Thomas

 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Samstag, 08. September 2018 um 17:05 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)

Thomas,
Thanks so much for getting back to me.  It feels very productive to have these interactions.

I'm not familiar with Excel VBA methods but can check documentation.  It might be a good idea to suggest that your users can check VBA documentation and maybe give them a link.
Thank you for showing me how to set ranges without using a name.  It makes perfect sense that you can assign a variable instead of a name to a range.

You example is mostly clear except for the last line:    workbook = Workbook.open('spec/data/workbook.xls')
    sheet = workbook.sheet(1)   
    col = sheet.col_range(1)
    col.Copy("destination" =>  s.row_range(3).ole_range)
I understand opening the workbook and worksheet then setting 'col' to the range of column 1.  I also understand that you are using the Copy method to copy column 1 to another location.  What I don't understand is:
- what is "destination"? The rocket equals ('=>') in Ruby means set an enum value and would use a ':name' type entry.  Am I right that statement intent is "col.Copy(:destination => s.row_range(3).ole_range)"?
- what is "s" in the destination s.row_range... ?  Did you mean "sheet"?  Were you showing how to copy to a different worksheet in this example (worksheet 's' instead of worksheet 'sheet')?

- are you copying column 1 to row 3, that is, transposing the column?  Is this how you would transpose?  Or did you intend to say 'col_range' rather than 'row_range'

- lastly, what does the ".ole_range" signify, that is, why is it required?  This is not something I've seen in your previous documentation.


I suspect some of the confusion comes from translating VBA syntax to Ruby syntax.
I'm surprised that copying a range between workbooks doesn't work.  I have copied individual cells between workbooks.  I fact, I've copied a range between workbooks using a loop to copy one cell at a time.  Now that I understand copying ranges a bit better, I'd think that setting up variables for a second workbook and worksheet would allow copying between them.  As in adding these lines to your example:    workbook2 = Workbook.open('spec/data/workbook2.xls')
    sheet2 = workbook2.sheet(1)
then, per your example:    col = sheet.col_range(1)    col.Copy("destination" => sheet2.row_range(3).ole_range)
At least, this is the form I'd expect for copying a range between workbooks - probably with the last line changed for Ruby per my earlier comments.

About the read-only problem, I had the same idea you suggested and wrote a little utility that executes 'RobustExcelOle::Excel.kill_all'.  Of course, you must be sure every other open Excel file is properly saved before using it so I may want to add a warning message.
I think I understand what 'reserved' is intended to do.  I can always create a new Excel instance for my program but anyone else opening a spreadsheet after that will likely start using my instance.  This means they get closed down along with me when I'm done.  This is the problem 'reserved' will solve

My only problem is that when my program has crashed I won't know when I reboot which open instance of Excel has been reserved for my use.  What if I write a reference to that instance into the same Setup spreadsheet that I use for reading other configuration parameters into the program when it boots.

Maybe you know if this will work?  I should test it.  If I can read in my Excel instance, I can also have my 'terminate Excel' utility read in and terminate just my program's Excel instance and not disrupt any other Excel activities on my system.  And if the program can't find the recorded instance, it can just create a new one and then write it to Setup.
Thanks again for all your great work.
Best,
Scott

**Comment by shbeavers** [comment]
It's all very clear now.  Thank you!

**Comment by Thomas008** [comment]
Dear Scott,

I now have commited an implementation of two things:

- Sheet#range: You can access a range consisting of one cell by providing the row and and the column of a cell.


 

  range = sheet.range(1,1) or a rectangular range
  range = sheet.range(1,1,3,4)

You can read the values by range.values

 

- Range#copy:

 

The destination may be one cell.

  range.copy(6,2)

If you provide a rectangular range as destination, the range might be copied several times.

  range.copy(10,1,30,30)

 

Best,

Thomas


---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Sonntag, 09. September 2018 um 00:06 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)

It's all very clear now.  Thank you!

**Comment by Thomas008** [comment]
Dear Scott,

in another commit, you can now copy ranges across into a worksheet of another workbook, and even of another Excel instance.

Best,

Thomas
 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Sonntag, 09. September 2018 um 00:06 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)

It's all very clear now.  Thank you!

**Comment by Thomas008** [comment]
Dear Scott,

in the new commit I improved the interface of accessing a range,

Sheet#range

such that you provide the rows and columns of a rectangular range via integer range, e.g.

sheet.range(1..2,1..4) (instead of sheet.range(1,1,2,4))

I guess, this is more of what you would expect.

Thank you,

Thomas
 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Sonntag, 09. September 2018 um 23:18 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)

Dear Thomas,
This is great news!  You work remarkably quickly.  Thank you for attending to these issues. 

These recent features - along with improved documentation - are excellent improvements to Robust.  I believe you have covered everything that I consider essential for programmatic control of Excel.  And you have contributed an excellent resource for programmers everywhere.

I wish you all the best in your future work.

Scott

**Comment by shbeavers** [comment]
Yes, a much more natural interface.  Nice!
I'm going quiet for a few days.  We're about to get hit directly with a very strong hurricane.  Very likely we won't have power or internet - or even cell service.

**Comment by Thomas008** [comment]
Dear Scott,

I consider to allow more address formats for ranges.

The address can be in r1c1- or a1-format.

Furthermore, the shall be *one* argument in the methods Sheet#range, Range#copy and ReoCommon#add_name.

So if the address consists of row and column, the address is sorrouned by brackets [].

For example, the following expressions are equivalent:


sheet.range([1..3,1..2])
sheet.range(["A".."B",1..2])

sheet.range("A1:B3")
sheet.range(["A1:B3"])

 

Example with a one-cell-range:

sheet.range([2,1])

sheet.range(["A2"])
sheet.range("A2")
 

Would this be okay for you?

Do you think of other useful formats?

 

Best,

Thomas

 

 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Mittwoch, 12. September 2018 um 23:18 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)

Yes, a much more natural interface.  Nice!
I'm going quiet for a few days.  We're about to get hit directly with a very strong hurricane.  Very likely we won't have power or internet - or even cell service.

**Comment by shbeavers** [comment]
Dear Thomas,
I think these address formats are excellent.  

At first, the option to use either "" or [""] when using the a1 format seemed superfluous.  However, your second example shows how this flexibility provides for mixed mode references, e.g. sheet(["A".."B",1..2]).  The rule is clear that quotes are required for any portion of the reference where a letter is involved, whether  "A" or "A1".

As a point of curiosity - and not because I think this would be a good feature - will the expression sheet["A"..2, 1..2] also work?  I could see how it might depending on the implementation logic.
Anyway, it's great to have both a1 and r1c1 formats as one or the other might be the most convenient to use at different times.
  
Scott

**Comment by Thomas008** [comment]
Dear Scott,

I'm glad that you are basically okay with allowing the other address formats.

The expression sheet["A"..2, 1..2] does not work so far, although I can also see it could be useful.

I did another commit with using this address format.
Best,

Thomas
 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Mittwoch, 26. September 2018 um 04:09 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)

Dear Thomas,
I think these address formats are excellent. 

At first, the option to use either "" or [""] when using the a1 format seemed superfluous.  However, your second example shows how this flexibility provides for mixed mode references, e.g. sheet(["A".."B",1..2]).  The rule is clear that quotes are required for any portion of the reference where a letter is involved, whether  "A" or "A1".

As a point of curiosity - and not because I think this would be a good feature - will the expression sheet["A"..2, 1..2] also work?  I could see how it might depending on the implementation logic.
Anyway, it's great to have both a1 and r1c1 formats as one or the other might be the most convenient to use at different times.
 
Scott

**Comment by shbeavers** [comment]
I think you offer plenty of flexibility without adding sheet["A"..2, 1..2].  It was just something I was curious about.

**Comment by Thomas008** [comment]
Dear Scott,

regarding the interface I decided to use

e.g. sheet.range([1..3,"B".."D"]) instead of sheet.range(["B".."D",1..3]),

i.e. to have the first parameter always the rows and the second parameter always the columns.

Best regards,

Thomas
 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Donnerstag, 27. September 2018 um 17:52 Uhr
Von: shbeavers <notifications@github.com>
An: Thomas008/robust_excel_ole <robust_excel_ole@noreply.github.com>
Cc: "Thomas R" <Thomas.Raths@gmx.net>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Thomas008/robust_excel_ole] Error in 'Range' Documentation (#5)

I think you offer plenty of flexibility without adding sheet["A"..2, 1..2].  It was just something I was curious about.

**Comment by shbeavers** [comment]
This makes very good sense.
